apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thumbops-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thumbops-agent.labels" . | nindent 4 }}
